apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: node-test
  labels:
    name: web
    app: node-test
spec:
  selector:
    name: web
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 80
      protocol: TCP